version: '3.8'

services:
  mongo:
    image: mongo:6.0
    restart: unless-stopped
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    environment:
      - MONGO_URI=mongodb://mongo:27017/itsaathi_admin
      - JWT_SECRET=itsaathi_super_secret_2026_change_this_now
      - CLIENT_URL=http://localhost:5173
      - ADMIN_EMAIL=admin@itsaathi.in
      - ADMIN_PASSWORD=Admin@12345
    ports:
      - "5000:5000"
    depends_on:
      - mongo

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - backend

volumes:
  mongo-data:
